export const AUTH_APP_NAME = 'TASK_MANAGER';
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const USERNAME_GENERATOR = 'USERNAME_GENERATOR';
export const JWT = 'JWT';
export const APP_GATEWAY = 'APP_GATEWAY';
export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';
